#spring:
#  datasource:

#  jpa:
#    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false

server:
  port: 8081



spring:
  datasource:
#    url: jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;FILE_LOCK=NO
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springdata
    username: keesun
    password: pass
    initialize: false
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
      temp:
        use_jdbc_metadata_defaults: false

logging:
  level:
    root: info

graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
    # specification and expectations of most clients, so use this option with caution
    introspection-enabled: true